name: Create GitHub Repository

on:
  workflow_dispatch:
    inputs:
      repo_name:
        description: 'Name of the new repository'
        required: true
      description:
        description: 'Description for the repo'
        required: false
      private:
        description: 'Should the repo be private? (true/false)'
        required: true
        default: 'true'

jobs:
  create_repo:
    runs-on: ubuntu-latest

    steps:
    - name: Create GitHub Repository
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        REPO_NAME: ${{ github.event.inputs.repo_name }}
        DESCRIPTION: ${{ github.event.inputs.description }}
        PRIVATE: ${{ github.event.inputs.private }}
      run: |
        curl -X POST https://api.github.com/user/repos \
          -H "Authorization: token $GH_TOKEN" \
          -H "Accept: application/vnd.github+json" \
          -d @- <<EOF
        {
          "name": "$REPO_NAME",
          "description": "$DESCRIPTION",
          "private": $PRIVATE
        }
        EOF
