name: Read group id from pom.xml

on:
  workflow_dispatch:

jobs:
  read-maven-info:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3  

      - name: Read and extract groupId and version from pom.xml
        id: groupid
        run: |
          # Extract the second <groupId> from pom.xml
          SECOND_GROUP_ID=$(grep '<groupId>' pom.xml | sed -n '2p' | sed -n 's:.*<groupId>\(.*\)</groupId>.*:\1:p')
          echo "Found second groupId: $SECOND_GROUP_ID"

          # Split it into parts by "."
          IFS='.' read -r PART1 PART2 PART3 PART4 PART5 <<< "$SECOND_GROUP_ID"

          # Output each part
          echo "part1=$PART1" >> $GITHUB_OUTPUT
          echo "part2=$PART2" >> $GITHUB_OUTPUT
          echo "part3=$PART3" >> $GITHUB_OUTPUT
          echo "part4=$PART4" >> $GITHUB_OUTPUT
          echo "part5=$PART5" >> $GITHUB_OUTPUT
