name: Read group id from pom.xml

on:
  workflow_dispatch:

jobs:
  read-maven-info:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Read groupId and version from pom.xml
        id: maven
        run: |
          GROUP_ID=$(xmllint --xpath "/*[local-name()='project']/*[local-name()='groupId']/text()" pom.xml)
          VERSION=$(xmllint --xpath "/*[local-name()='project']/*[local-name()='version']/text()" pom.xml)
          echo "GROUP_ID=$GROUP_ID"
          echo "VERSION=$VERSION"
          echo "group_id=$GROUP_ID" >> $GITHUB_OUTPUT
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Use output
        run: |
          echo "Group ID: ${{ steps.maven.outputs.group_id }}"
          echo "Version: ${{ steps.maven.outputs.version }}"
